auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “SikiLiu's Blog”
title: SiKiLiu's blog
description: Everything about SiKiLiu.
url: http://sikiliu.github.io
feed: /atom.xml
author_info: <a href="http://sikiliu.github.io/">SiKiLiu</a>
